---
grafana_security:
  admin_user: admin
  admin_password: admin

grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: 'http://localhost:9090'
    basicAuth: false

grafana_dashboards:
  - dashboard_id: 1860
    revision_id: 23
    datasource: prometheus

  - dashboard_id: 159
    revision_id: 5
    datasource: prometheus

  - dashboard_id: 13196
    revision_id: 5
    datasource: prometheus
