---
prometheus_version: '2.29.1'

prometheus_config_dir: /etc/prometheus
prometheus_db_dir: /var/lib/prometheus

prometheus_scrape_configs:
  - job_name: prometheus
    metrics_path: "/metrics"
    static_configs:
      - targets:
        - "localhost:9100"

  - job_name: node
    file_sd_configs:
      - files:
        - "{{ prometheus_config_dir }}/file_sd/node.yml"

prometheus_targets:
  node:
    - targets:
        - localhost:9100
      labels:
        env: node
