---
roles:
  - name: cloudalchemy.node_exporter
  - name: cloudalchemy.prometheus
    src: https://github.com/cloudalchemy/ansible-prometheus
    version: master
  - name: cloudalchemy.alertmanager
  - name: cloudalchemy.grafana

collections:
  - name: community.general
  - name: ansible.posix
  - name: nginxinc.nginx_core
