---
- name: 'Deploy & configure Grafana'
  hosts: '{{ host }}'
  become: true

  vars_files:
    - vars/monitoring/main.yml
    - vars/monitoring/grafana.yml

  handlers:
    - include: handlers/main.yml

  pre_tasks:
    - name: Check if ansible cannot be run here
      stat:
        path: /etc/no-ansible
      register: no_ansible

    - name: Verify if we can run ansible
      assert:
        that:
          - "not no_ansible.stat.exists"
        success_msg: "We are able to run on this node"
        fail_msg: "/etc/no-ansible exists - skipping run on this node"

  roles:
    - role: cloudalchemy.grafana
      state: present

  post_tasks:
    - name: Open firewalld ports
      ansible.posix.firewalld:
        port: "3000"
        permanent: true
        state: enabled

    - name: Touching run file that ansible has ran here
      file:
        path: /var/log/ansible.run
        state: touch
        mode: '0644'
        owner: root
        group: root
